### ISSUE TITLE
On windows more than 2 to 3 target destinations during ./mc cp fails as below sporadically

### ISSUE THREAD

**Issue by GarimaKapoor** [minio-io/mc#281]
```
created by main.doPutMultiTarget
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:58 +0xe7

goroutine 1 [runnable, locked to thread]:
syscall.(*Proc).Call(0xc0820044c0, 0xc082155128, 0x2, 0x2, 0x20, 0x7b2580, 0x0,
0x0)
        c:/go/src/syscall/dll_windows.go:132 +0x36e
syscall.(*LazyProc).Call(0xc082007ec0, 0xc082155128, 0x2, 0x2, 0xc082112100, 0x1
, 0x0, 0x0)
        c:/go/src/syscall/dll_windows.go:279 +0x74
github.com/shiena/ansicolor.getConsoleScreenBufferInfo(0x1c, 0xc08200a140)
        C:/Users/Garima Kapoor/Go/src/github.com/shiena/ansicolor/ansicolor_wind
ows.go:159 +0xaa
github.com/shiena/ansicolor.changeColor(0xc08202a27c, 0x1, 0x40)
        C:/Users/Garima Kapoor/Go/src/github.com/shiena/ansicolor/ansicolor_wind
ows.go:208 +0x4f
github.com/shiena/ansicolor.parseEscapeSequence(0xc08202a26d, 0xc08202a27c, 0x1,
 0x40)
        C:/Users/Garima Kapoor/Go/src/github.com/shiena/ansicolor/ansicolor_wind
ows.go:259 +0x4d
github.com/shiena/ansicolor.(*ansiColorWriter).Write(0xc08202a240, 0xc0821cc0a0,
 0x4, 0x50, 0x2, 0x0, 0x0)
        C:/Users/Garima Kapoor/Go/src/github.com/shiena/ansicolor/ansicolor_wind
ows.go:302 +0x4cb
fmt.Fprintf(0x181d80, 0xc08202a240, 0x7f0bb0, 0x6, 0xc082155438, 0x2, 0x2, 0x421
940, 0x0, 0x0)
        c:/go/src/fmt/print.go:189 +0xb3
github.com/fatih/color.Unset()
        C:/Users/Garima Kapoor/Go/src/github.com/fatih/color/color.go:79 +0x171
github.com/fatih/color.(*Color).Println(0xc082004fa0, 0x0, 0x0, 0x0, 0x1, 0x0, 0
x0)
        C:/Users/Garima Kapoor/Go/src/github.com/fatih/color/color.go:130 +0xf0
main.colorPrintln(0xc082004fa0, 0xc082155710, 0x1, 0x1)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/colors.go:64 +0x77
main.info(0xc082155710, 0x1, 0x1)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/colors.go:41 +0xe2
main.multiCopy(0xc08206a190, 0x4, 0x7, 0xc082007f80, 0x27, 0x0, 0x0)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:123 +0xd7
5
main.doCopyCmd(0xc08209e1e0)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:143 +0x30
2
github.com/minio-io/cli.Command.Run(0x7fbab0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x83
3b70, 0x16, 0x890d70, ...)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/cli/command.go:123 +0x
1074
github.com/minio-io/cli.(*App).Run(0xc082078300, 0xc082010070, 0x7, 0x7, 0x0, 0x
0)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/cli/app.go:181 +0x85d
github.com/minio-io/cli.(*App).RunAndExitOnError(0xc082078300)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/cli/app.go:192 +0x5e
main.main()
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/main.go:114 +0x1fc

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc082066170, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044070, 0xc082066060, 0x7f91b0, 0x7, 0x8b49e8, 0x3, 0x
0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082066000, 0xc082162000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044080, 0xc082162000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc08202d350, 0x1836f0, 0xc082044080, 0x5, 0x0
, 0x0)
        c:/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc082068000, 0x17, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc082068000, 0xc08200f000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        c:/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x183ba0, 0xc082068000, 0xc082052108, 0xc08200f000,
0x1000, 0x1000, 0x740140, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc0820b8180, 0xc08200f000, 0x1000, 0x1000, 0xc08
2012000, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc082028d20)
        c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc082028d20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc0820520b0)
        c:/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc0820520b0)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 12 [select]:
net/http.(*persistConn).roundTrip(0xc0820524d0, 0xc0820c2f70, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1082 +0x7b4
net/http.(*Transport).RoundTrip(0xc08202a3f0, 0xc0820205b0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:235 +0x55f
github.com/minio-io/mc/pkg/client/s3.RoundTripTrace.RoundTrip(0x1823c8, 0x9e80a8
, 0x182000, 0xc08202a3f0, 0xc0820205b0, 0xc082011594, 0x0, 0x0)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/pkg/client/s3/httpt
race.go:51 +0x187
github.com/minio-io/mc/pkg/client/s3.(*RoundTripTrace).RoundTrip(0xc0820b8400, 0
xc0820205b0, 0xc082007fb8, 0x0, 0x0)
        <autogenerated>:20 +0xc3
github.com/minio-io/mc/pkg/client/s3.(*s3Client).Put(0xc0820c2c30, 0xc082007fc9,
 0x8, 0xc082007fd2, 0x1, 0xc0820bc3f1, 0x20, 0x111b1f0, 0x183da0, 0xc082044058,
...)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/pkg/client/s3/objec
t.go:73 +0x33d
main.multiTargetGoroutine(0xc082007fb0, 0x23, 0xc0820bc3f1, 0x20, 0x111b1f0, 0x1
83da0, 0xc082044058, 0xc082028e40)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:48 +0x319

created by main.doPutMultiTarget
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:58 +0xe7

goroutine 13 [select]:
net/http.(*persistConn).roundTrip(0xc082052580, 0xc0820c32c0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1082 +0x7b4
net/http.(*Transport).RoundTrip(0xc08202a3f0, 0xc082020820, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:235 +0x55f
github.com/minio-io/mc/pkg/client/s3.RoundTripTrace.RoundTrip(0x1823c8, 0x9e80a8
, 0x182000, 0xc08202a3f0, 0xc082020820, 0xc082011de4, 0x0, 0x0)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/pkg/client/s3/httpt
race.go:51 +0x187
github.com/minio-io/mc/pkg/client/s3.(*RoundTripTrace).RoundTrip(0xc0820b8920, 0
xc082020820, 0xc08202c008, 0x0, 0x0)
        <autogenerated>:20 +0xc3
github.com/minio-io/mc/pkg/client/s3.(*s3Client).Put(0xc0820c2f90, 0xc08202c019,
 0x8, 0xc08202c022, 0x1, 0xc0820bc3f1, 0x20, 0x111b1f0, 0x183da0, 0xc0820440a0,
...)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/pkg/client/s3/objec
t.go:73 +0x33d
main.multiTargetGoroutine(0xc08202c000, 0x23, 0xc0820bc3f1, 0x20, 0x111b1f0, 0x1
83da0, 0xc0820440a0, 0xc082028e40)
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:48 +0x319

created by main.doPutMultiTarget
        C:/Users/Garima Kapoor/Go/src/github.com/minio-io/mc/cmd-cp.go:58 +0xe7

goroutine 29 [select]:
net/http.(*persistConn).writeLoop(0xc0820526e0)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 33 [select]:
net/http.(*persistConn).writeLoop(0xc082052580)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 31 [select]:
net/http.(*persistConn).writeLoop(0xc082052630)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 26 [runnable]:
net.(*pollDesc).Wait(0xc0820662f0, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044070, 0xc0820661e0, 0x7f91b0, 0x7, 0x8b49e8, 0xfffff
ffffffffffb, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082066180, 0xc08206d000, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044240, 0xc08206d000, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820bd4a0, 0x1836f0, 0xc082044240, 0x5, 0x0
, 0x0)
        c:/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc082068580, 0x17, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc082068580, 0xc0820af000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        c:/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x183ba0, 0xc082068580, 0xc082052528, 0xc0820af000,
0x1000, 0x1000, 0x170010, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc082140140, 0xc0820af000, 0x1000, 0x1000, 0xc08
1ffbbf9, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc0820286c0)
        c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc0820286c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc0820524d0)
        c:/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 30 [IO wait]:
net.(*pollDesc).Wait(0xc0820665f0, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044070, 0xc0820664e0, 0x7f91b0, 0x7, 0x8b49e8, 0xc0820
87b80, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082066480, 0xc08206d800, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044260, 0xc08206d800, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820bd560, 0x1836f0, 0xc082044260, 0x5, 0x0
, 0x0)
        c:/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc082068840, 0x17, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc082068840, 0xc082147000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        c:/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x183ba0, 0xc082068840, 0xc082052688, 0xc082147000,
0x1000, 0x1000, 0xc0820e2080, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc082140380, 0xc082147000, 0x1000, 0x1000, 0xc08
2012000, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc082028d80)
        c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc082028d80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc082052630)
        c:/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 32 [runnable]:
net.(*pollDesc).Wait(0xc082066470, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044070, 0xc082066360, 0x7f91b0, 0x7, 0x8b49e8, 0x0, 0x
0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082066300, 0xc08210a000, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044280, 0xc08210a000, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820bd620, 0x1836f0, 0xc082044280, 0x5, 0x0
, 0x0)
        c:/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc082068b00, 0x17, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc082068b00, 0xc0820db000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        c:/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x183ba0, 0xc082068b00, 0xc0820525d8, 0xc0820db000,
0x1000, 0x1000, 0x170010, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc082140480, 0xc0820db000, 0x1000, 0x1000, 0xc08
1ffbbf5, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc082029140)
        c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc082029140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc082052580)
        c:/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 28 [IO wait]:
net.(*pollDesc).Wait(0xc082066770, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044070, 0xc082066660, 0x7f91b0, 0x7, 0x8b49e8, 0xc0820
87810, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082066600, 0xc08210a800, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc0820442a0, 0xc08210a800, 0x400, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820bd6e0, 0x1836f0, 0xc0820442a0, 0x5, 0x0
, 0x0)
        c:/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc082068dc0, 0x17, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc082068dc0, 0xc082143000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        c:/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x183ba0, 0xc082068dc0, 0xc082052738, 0xc082143000,
0x1000, 0x1000, 0xc0820e2300, 0x0, 0x0)
        c:/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc082140280, 0xc082143000, 0x1000, 0x1000, 0xc08
2012000, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc082028960)
        c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc082028960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc0820526e0)
        c:/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 27 [select]:
net/http.(*persistConn).writeLoop(0xc0820524d0)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3
```

Here is the command line used

```
C:\Users\Garima Kapoor>mc cp https://s3.amazonaws.com/ddd/chrome.dll https://s3.
amazonaws.com/minioinc/1 https://s3.amazonaws.com/minioinc/2 https://s3.amazonaw
s.com/minioinc/3 https://s3.amazonaws.com/minioinc/4
```

**Comment by GarimaKapoor** [comment]
NOTE :  Not reproducible all the time

**Comment by harshavardhana** [comment]
LGTM
