### ISSUE TITLE
mc panics on no access

### ISSUE THREAD

**Issue by fkautz** [minio-io/mc#510]
Writing to a bucket where we have no access, get this nice little error message:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4dbb66]

goroutine 11 [running]:
github.com/minio-io/mc/pkg/client/s3.func·001()
	/home/fkautz/gopath/src/github.com/minio-io/mc/pkg/client/s3/object_put.go:72 +0x826
created by github.com/minio-io/mc/pkg/client/s3.(*s3Client).Put
	/home/fkautz/gopath/src/github.com/minio-io/mc/pkg/client/s3/object_put.go:87 +0x373

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0xc2081a70a0)
	/usr/local/go/src/sync/waitgroup.go:132 +0x169
github.com/minio-io/mc/pkg/client/s3.(*BlockingWriteCloser).Close(0xc20824d5f0, 0x0, 0x0)
	/home/fkautz/gopath/src/github.com/minio-io/mc/pkg/client/s3/object_put.go:114 +0xa6
main.doCopyCmd(0x7ff86b872308, 0x9fca30, 0xc20803d710, 0xc20803d830, 0x0, 0x0, 0x0, 0x0)
	/home/fkautz/gopath/src/github.com/minio-io/mc/cmd-cp.go:139 +0x8a2
main.runCopyCmd(0xc2080b81e0)
	/home/fkautz/gopath/src/github.com/minio-io/mc/cmd-cp.go:90 +0x10f5
github.com/minio-io/cli.Command.Run(0x8087d0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x836610, 0x16, 0x0, ...)
	/home/fkautz/gopath/src/github.com/minio-io/mc/Godeps/_workspace/src/github.com/minio-io/cli/command.go:123 +0x106d
github.com/minio-io/cli.(*App).Run(0xc208072300, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
	/home/fkautz/gopath/src/github.com/minio-io/mc/Godeps/_workspace/src/github.com/minio-io/cli/app.go:181 +0x856
github.com/minio-io/cli.(*App).RunAndExitOnError(0xc208072300)
	/home/fkautz/gopath/src/github.com/minio-io/mc/Godeps/_workspace/src/github.com/minio-io/cli/app.go:192 +0x57
main.main()
	/home/fkautz/gopath/src/github.com/minio-io/mc/main.go:117 +0x1e4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc208010a00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010a00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080109a0, 0xc20800cc00, 0x400, 0x400, 0x0, 0x7ff86b871c80, 0xc2081e8e10)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080500c8, 0xc20800cc00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20803d6e0, 0x7ff86b8735a8, 0xc2080500c8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20807e000, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20807e000, 0xc208087000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7ff86b877f30, 0xc20807e000, 0xc2080a2108, 0xc208087000, 0x1000, 0x1000, 0xc20800aac0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081a6f00, 0xc208087000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20823c7e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20823c7e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080a20b0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc2080a20b0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 12 [sleep]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc2080b84b0)
	/home/fkautz/gopath/src/github.com/minio-io/mc/Godeps/_workspace/src/github.com/cheggaaa/pb/pb.go:332 +0x62
created by github.com/cheggaaa/pb.(*ProgressBar).Start
	/home/fkautz/gopath/src/github.com/minio-io/mc/Godeps/_workspace/src/github.com/cheggaaa/pb/pb.go:101 +0xa8

goroutine 16 [runnable]:
net.(*pollDesc).Wait(0xc2081ed5d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081ed5d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081ed570, 0xc20820e000, 0x400, 0x400, 0x0, 0x7ff86b871c80, 0xc208253fd0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208050130, 0xc20820e000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20824d9e0, 0x7ff86b8735a8, 0xc208050130, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20807f080, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20807f080, 0xc208237000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7ff86b877f30, 0xc20807f080, 0xc20824a9f8, 0xc208237000, 0x1000, 0x1000, 0x7ff86b860010, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082472a0, 0xc208237000, 0x1000, 0x1000, 0xc207ffafea, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20823d920)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20823d920, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20824a9a0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 18 [runnable]:
net/http.(*persistConn).writeLoop(0xc20824a9a0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by fkautz** [comment]
Issue fixed, removed a defer res.Body.Close()
